# Generated by Django 4.2.11 on 2024-09-24 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='resume',
            new_name='resume_id',
        ),
    ]
