# Generated by Django 4.2.11 on 2024-07-13 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='link',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
