# Generated by Django 4.2.11 on 2024-09-24 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0002_rename_resume_jobapplication_resume_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobapplication',
            old_name='resume_id',
            new_name='resume',
        ),
    ]
