# Generated by Django 4.2.11 on 2024-07-13 15:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobPlatform', '0002_job_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='password',
        ),
        migrations.AddField(
            model_name='provider',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='provider',
            name='company_logo',
            field=models.ImageField(upload_to='Company/'),
        ),
        migrations.AlterField(
            model_name='provider',
            name='company_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='provider',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='provider',
            name='provider_name',
            field=models.CharField(max_length=255),
        ),
    ]
