# Generated by Django 5.1 on 2024-08-12 06:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobPlatform", "0003_remove_provider_password_provider_user_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="quantity_in_stock",
            new_name="vaccencies",
        ),
        migrations.RemoveField(
            model_name="job",
            name="reorder_level",
        ),
        migrations.AddField(
            model_name="job",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
    ]
