# Generated by Django 5.1 on 2024-08-12 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobPlatform", "0004_rename_quantity_in_stock_job_vaccencies_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="skills",
            field=models.CharField(default="exit", max_length=255),
            preserve_default=False,
        ),
    ]
