# Generated by Django 5.1 on 2024-08-12 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobPlatform", "0005_job_skills"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.CharField(default="exit", max_length=255),
            preserve_default=False,
        ),
    ]
