# Generated by Django 5.1 on 2024-08-12 06:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobPlatform", "0006_job_experience"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="vaccencies",
            new_name="vacancie",
        ),
    ]
