# Generated by Django 5.1 on 2024-08-12 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("jobPlatform", "0007_rename_vaccencies_job_vacancie"),
    ]

    operations = [
        migrations.RenameField(
            model_name="job",
            old_name="vacancie",
            new_name="vacancies",
        ),
    ]
