# Generated by Django 4.2.11 on 2024-08-20 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0008_rename_vacancie_job_vacancies'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='location',
            field=models.CharField(default='exit', max_length=255),
            preserve_default=False,
        ),
    ]
