# Generated by Django 4.2.11 on 2024-09-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0010_resumeupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='till_date',
            field=models.DateField(null=True, blank=True),  # Allow null and blank values
        ),
    ]
