# Generated by Django 4.2.11 on 2024-09-13 11:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobPlatform', '0013_rename_created_at_job_created_on'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingJobLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobPlatform.job')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobPlatform.provider')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobPlatform.resumeupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
