# Generated by Django 4.2.11 on 2024-09-13 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0014_missingjoblink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='link',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='job',
            name='till_date',
            field=models.DateField(null=True),
        ),
    ]
