# Generated by Django 4.2.11 on 2024-09-13 11:39

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobPlatform', '0015_alter_job_link_alter_job_till_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MissingJobLink',
            new_name='JobApplication',
        ),
    ]
