# Generated by Django 4.2.11 on 2024-09-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0016_rename_missingjoblink_jobapplication'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='customer',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='jobPlatform.customer'),
            preserve_default=False,
        ),
    ]
