# Generated by Django 4.2.11 on 2024-09-15 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0018_jobapplication_reviewed'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
