# Generated by Django 4.2.11 on 2024-09-15 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0019_jobapplication_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobapplication',
            name='reviewed',
        ),
    ]
