# Generated by Django 4.2.11 on 2024-09-16 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0021_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_provider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(max_length=2000)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobPlatform.customer')),
            ],
        ),
    ]
