# Generated by Django 4.2.11 on 2024-09-16 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0022_contact_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('job_expiry', 'Job Expiry'), ('job_expired', 'Job Expired'), ('new_application', 'New Application')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobPlatform.provider')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact_provider',
        ),
    ]
