# Generated by Django 4.2.11 on 2024-09-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0024_alter_notification_notification_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='username',
            field=models.CharField(default='exit', max_length=100),
            preserve_default=False,
        ),
    ]
