# Generated by Django 4.2.11 on 2024-09-16 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0025_admin_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
