# Generated by Django 4.2.11 on 2024-09-18 16:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0029_contact_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcategory',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
