# Generated by Django 4.2.11 on 2024-09-21 12:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0032_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provider',
            name='company_logo',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
