# Generated by Django 4.2.11 on 2024-09-21 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('jobPlatform', '0033_alter_provider_company_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumeupload',
            name='fileName',
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
