# Generated by Django 4.2.11 on 2024-09-22 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('jobPlatform', '0034_resumeupload_filename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resumeupload',
            name='fileName',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='resumeupload',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
