from django.conf import settings
from django.conf.urls.static import static
from django.urls import path
from . import views

urlpatterns = [
    path('',views.index,name='index'),
    path('customer_dashboard/',views.customer_dashboard,name='customer_dashboard'),
    path('reg1/',views.reg1,name='reg1'),
    path('log1/',views.log1,name='log1'),
    path('login_provider/',views.login_provider,name='login_provider'),
    path('login_customer/',views.login_customer,name='login_customer'),
    path('register_provider/',views.register_provider,name='register_provider'),
    path('register_customer/',views.register_customer,name='register_customer'),
    path('change_password/', views.change_password, name='change_password'),
    path('reset_password/<uidb64>/<token>/', views.reset_password, name='reset_password'),
    path('logout/', views.user_logout, name='logout'),
    path('edit_customer/', views.edit_customer, name='edit_customer'),
    path('contact/', views.contact_process, name='contact_process'),
    path('contact/success/', views.contact_success, name='contact_success'),
    path('voice_search/', views.voice_search, name='voice_search'),
    path('category_jobs/<int:category_id>/', views.category_jobs, name='category_jobs'),
    path('jobs/', views.job_list, name='job_list'),
    path('about', views.about, name='about'),
    path('single_blog', views.single_blog, name='single_blog'),
    path('blog', views.blog, name='blog'),
    path('elements', views.elements, name='elements'),
    path('contact/', views.contact_process, name='contact_process'),
    path('provider_index/', views.provider_index, name='provider_index'),
    path('edit_provider/', views.edit_provider, name='edit_provider'),
    path('add-job/', views.add_job, name='add_job'),
    path('job_details/<int:id>/', views.job_details, name='job_details'),  # Ensure this view exists
    path('upload/', views.analyze_resume, name='analyze_resume'),
    path('jobcv/<str:job_title>/', views.jobcv, name='jobcv'),
    path('manage-jobs/', views.manage_jobs, name='manage_jobs'),
    path('edit-job/<int:job_id>/', views.edit_job, name='edit_job'),
    path('delete-job/<int:job_id>/', views.delete_job, name='delete_job'),
    path('handle_no_link/<int:user_id>/<int:job_id>/', views.handle_no_link, name='handle_no_link'),
    path('thank_you_page/', views.thank_you_page, name='thank_you_page'),  # Example thank you page
    path('applied-jobs/', views.applied_jobs, name='applied_jobs'),
    path('cancel-application/<int:application_id>/', views.cancel_application, name='cancel_application'),
    path('jobs/<int:id>/', views.job_detail, name='job_detail'),  # Detail page route
    path('contact/', views.contact_view, name='contact'),
    path('search/', views.search_jobs, name='job_search'),
    path('applications/', views.provider_applications, name='provider_applications'),
    path('applications/mark-reviewed/', views.mark_reviewed, name='mark_reviewed'),
    path('applications_page/', views.applications_page, name='applications_page'),
    path('applications/new/', views.new_applications, name='new_applications'),
    path('applications/shortlisted/', views.shortlisted_applications, name='shortlisted_applications'),
    path('applications/hired/', views.hired_applications, name='hired_applications'),
    path('applications/rejected/', views.rejected_applications, name='rejected_applications'),
    path('application_detail/<int:application_id>/', views.application_detail, name='application_detail'),
    path('applications/update-status/<int:application_id>/', views.update_application_status, name='update_application_status'),
    path('profile_opt/', views.profile_opt, name='profile_opt'),
    path('edit_pass/', views.edit_pass, name='edit_pass'),
    path('provider/forgot_password/', views.forgot_password, name='forgot_password'),
    path('provider/reset-password/<uidb64>/<token>/', views.reset_password, name='reset_password'),
    path('customer/forgot_password/', views.forgot_password_customer, name='forgot_password'),
    path('customer/reset-password/<uidb64>/<token>/', views.reset_password_customer, name='reset_password'),
    path('customer/password_change_form/', views.password_change_form, name='password_change_form'),
    path('provider/notifications/', views.notifications, name='notifications'),
    path('provider/notifications/mark-as-read/<int:notification_id>/', views.mark_as_read, name='mark_as_read'),
    path('notifications/delete/<int:notification_id>/', views.delete_notification, name='delete_notification'),

    #Admin
    path('admin-login/', views.custom_admin_login, name='admin_login'),
    path('admin-dashboard/', views.admin_dashboard, name='admin_dashboard'),
    path('form/', views.form, name='form'),
    path('edit-admin-details/', views.edit_admin_details, name='edit_admin_details'),
    path('messages/', views.messages_dropdown, name='messages_dropdown'),
    path('all-messages/', views.all_messages, name='messages_list'),
    path('table/', views.table, name='table'),
    path('delete_message/<int:message_id>/', views.delete_message, name='delete_message'),
    path('view_message/<int:message_id>/', views.view_message, name='view_message'),
    path('all-providers/', views.all_providers, name='provider_list'),
    path('view_provider/<int:provider_id>/', views.view_provider, name='view_provider'),
    path('all-customers/', views.all_customers, name='customer_list'),
    path('view_customer/<int:customer_id>/', views.view_customer, name='view_customer'),
    path('button/', views.button, name='button'),
    path('applications/new_admin/', views.new_applications_admin, name='new_applications_admin'),
    path('applications/shortlisted_admin/', views.shortlisted_applications_admin, name='shortlisted_applications_admin'),
    path('applications/hired_admin/', views.hired_applications_admin, name='hired_applications_admin'),
    path('applications/rejected_admin/', views.rejected_applications_admin, name='rejected_applications_admin'),
    path('application_detail/<int:application_id>/', views.application_detail, name='application_detail'),
    path('add-category/', views.add_category, name='add_category'),
    path('categories/', views.category_list, name='category_list'),
    path('edit-category/<int:category_id>/', views.edit_category, name='edit_category'),
    path('jobs/', views.job_list, name='job_list'),
    path('expired-jobs/', views.expired_jobs, name='expired_jobs'),
    path('provider-registration-chart/', views.provider_registration_chart, name='provider_registration_chart'),
    path('customer-registration-chart/', views.customer_registration_chart, name='customer_registration_chart'),
    path('job-posting-chart/', views.job_posting_chart, name='job_posting_chart'),
    path('job-category-distribution/', views.job_category_distribution, name='job_category_distribution'),
    path('application-status-distribution/', views.application_status_distribution, name='application_status_distribution'),
    path('job-postings-and-application-ratio/', views.job_postings_and_application_ratio, name='job_postings_and_application_ratio'),
    path('filter-providers-by-date/', views.filter_providers_by_date, name='filter_providers_by_date'),
    path('filter-customers/', views.filter_customers_by_date, name='filter_customers_by_date'),
    path('filter-jobs/', views.filter_jobs_by_date, name='filter_jobs_by_date'),
    path('search_admin/', views.search_results_admin, name='search_results_admin'),
    path('forgot-password/', views.forgot_password_admin, name='forgot_password_admin'),
    path('forgot-password/reset-password-admin/<uuid:token>/', views.reset_password_admin, name='reset_password_admin'), 

]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


    

